apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-apps
  namespace: thomas-ns
  labels:
    app: gitea-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-apps
  template:
    metadata:
      labels:
        app: gitea-apps
    spec:
      containers:
        - name: gitea
          image: thfx31/ynov:gitea-v1
          env:
            - name: GITEA__database__DB_TYPE
              value: postgres
            - name: GITEA__database__HOST
              value: gitea-postgres:5432
            - name: GITEA__database__NAME
              value: gitea
            - name: GITEA__database__USER
              value: gitea
            - name: GITEA__database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: gitea-db-secret
                  key: password
          volumeMounts:
            - name: gitea-data
              mountPath: /data

      imagePullSecrets:
        - name: dockerhub-secret

      volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-pvc

