apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-postgres
  namespace: thomas-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-postgres
  template:
    metadata:
      labels:
        app: gitea-postgres
    spec:
      containers:
        - name: postgres
          image: thfx31/ynov:postgres-v1
          env:
            - name: POSTGRES_DB
              value: gitea
            - name: POSTGRES_USER
              value: gitea
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitea-db-secret
                  key: password
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      imagePullSecrets:
        - name: dockerhub-secret
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: gitea-postgres-pvc
